server:
  port: 8082

spring:
  application:
    name: springboot-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8070
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}-flow-rules
            group-id: SENTINEL_GROUP
            rule-type: flow
            data-type: json
        degrade:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}-degrade-rules
            group-id: SENTINEL_GROUP
            rule-type: degrade
            data-type: json
        param:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}-param-rules
            group-id: SENTINEL_GROUP
            rule-type: param-flow
            data-type: json
# 47.93.245.76
dubbo:
  application:
    name: springboot-service
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.lcyanxi.service.impl

apollo:
  bootstrap:
    enabled: true
    namespaces: commonConfig,dubboLimitConfig,INFRA.redis

