server:
  port: 8082

spring:
  application:
    name: springboot-service

dubbo:
  application:
    name: springboot-service
  registry:
    address: nacos://47.93.245.76:8848
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.lcyanxi.service.impl

apollo:
  bootstrap:
    enabled: true
    namespaces: commonConfig,dubboLimitConfig,INFRA.redis

