server:
  port: 8082


dubbo:
  application:
    name: springboot-dubbo-server
  registry:
    protocol: zookeeper
    address: lcyanxi.com:2181,lcyanxi.com:2182,lcyanxi.com:2183
    timeout: 60000
  protocol:
    name: dubbo
    port: 20880
  version: 1.0.0
  provider:
    filter:guavaDefaultLimitFlowFilter
  scan:
    base-packages: com.lcyanxi.service.impl


