server:
  port: 8082


dubbo:
  application:
    name: springboot-dubbo-server
  registry:
    protocol: nacos
#    address: lcyanxi.com:2181,lcyanxi.com:2182,lcyanxi.com:2183
    address: lcyanxi.com:8848
  protocol:
    name: dubbo
    port: 20880
  version: 1.0.0

  scan:
    base-packages: com.lcyanxi.service.impl

app:
  id: lcyanxi-spring-service
apollo:
  meta: http://localhost:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true

logging:
  level:
    com:
      gf:
        controller: debug
