server:
  port: 8082

spring:
  application:
    name: springboot-service

dubbo:
  application:
    name: springboot-service
  registry:
#    address: lcyanxi.com:2181,lcyanxi.com:2182,lcyanxi.com:2183
    address: nacos://lcyanxi.com:8848
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.lcyanxi.service.impl

app:
  id: springboot-service
apollo:
  meta: http://localhost:8080
  bootstrap:
    enabled: true
    namespaces: application,commonConfig,ratelimiter
    eagerLoad:
      enabled: true

