server:
  port: 8081

spring:
  application:
    name: springboot-manage
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    password: lc121718
    timeout: 10000

dubbo:
  application:
    name: springboot-manage
  registry:
    address: nacos://localhost:8848
  consumer:
    timeout: 30000

apollo:
  bootstrap:
    enabled: true
    namespaces: manage-application,INFRA.redis
