server:
  port: 8081

spring:
  application:
    name: springboo-manage

dubbo:
  application:
    name: springboot-manage
  registry:
    address: nacos://lcyanxi.com:8848
  consumer:
    timeout: 30000

app:
  id: springboot-manage
apollo:
  meta: http://localhost:8080
  bootstrap:
    enabled: true
    namespaces: application
    eagerLoad:
      enabled: true
