server:
  port: 9999

spring:
  application:
    name: springboot-manage
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    password: lc121718
    timeout: 10000
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8070
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}-flow-rules
            group-id: SENTINEL_GROUP
            rule-type: flow
            data-type: json
        degrade:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}-degrade-rules
            group-id: SENTINEL_GROUP
            rule-type: degrade
            data-type: json
        param:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}-param-rules
            group-id: SENTINEL_GROUP
            rule-type: param-flow
            data-type: json
        system:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}-system-rules
            group-id: SENTINEL_GROUP
            rule-type: system
        authority:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}-authority-rules
            group-id: SENTINEL_GROUP
            rule-type: authority
dubbo:
  application:
    name: springboot-manage
  registry:
    address: nacos://localhost:8848
  consumer:
    timeout: 30000
    check: false

apollo:
  bootstrap:
    enabled: true
    namespaces: manage-application,INFRA.redis
