server:
  port: 8081

spring:
  application:
    name: springboo-manage

dubbo:
  application:
    name: springboot-manage
  registry:
    address: nacos://lcyanxi.com:8848
  consumer:
    timeout: 30000

apollo:
  meta: http://localhost:8080
  bootstrap:
    enabled: true
    namespaces: manage-application,INFRA.redis
